// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThiccDaddie.ReplayManager.Server.DataAccess;

namespace ThiccDaddie.ReplayManager.Server.Migrations
{
    [DbContext(typeof(ReplayInfoContext))]
    [Migration("20200903210532_ChangeReplayInfoDateTimeType")]
    partial class ChangeReplayInfoDateTimeType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("ThiccDaddie.ReplayManager.Shared.ReplayInfo", b =>
                {
                    b.Property<string>("ReplayInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BattleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientVersionFromExe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFilePresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerVehicle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.HasKey("ReplayInfoId");

                    b.ToTable("ReplayInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
