# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - v0.*
    - test

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  rid: 'win-x64'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.x'
  inputs:
    packageType: 'sdk'
    version: '3.x'
- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/ReplayManager.Server.csproj'
    publishWebProjects: false
    arguments: '--no-restore -r $(rid) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)/$(rid)'
    zipAfterPublish: true
- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: drop
- task: GitHubRelease@1
  displayName: 'Create GitHub Release'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')
  inputs:
    gitHubConnection: 'github.com_ThiccDaddie'
    repositoryName: 'ThiccDaddie/ReplayManager'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'release-v*'
    releaseNotesSource: 'inline'
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'