# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - release-v*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'  

jobs: 
- job: build_and_publish
  strategy:
    matrix: 
      x86:
        platform: x86
        rid: 'win-x86'
      x64: 
        platform: x64
        rid: 'win-x64'
    maxParallel: 2

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.x'
    inputs:
      packageType: 'sdk'
      version: '3.x'
  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - $(buildConfiguration)'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/ReplayManager.Server.csproj'
      arguments: '--no-restore -r $(rid) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)/$(platform)'
      zipAfterPublish: false
  - task: MSBuild@1
    inputs:
      solution: '**/*.Installer.wixproj'
      msbuildArchitecture: x64
      platform: '$(platform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/p:Version=1.2.3.4 /p:BinPath=$(Build.ArtifactStagingDirectory)/$(buildConfiguration)/$(platform)/Server /p:OutputPath=$(Build.ArtifactStagingDirectory)/installers/$(buildConfiguration)/$(platform)'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/installers/$(buildConfiguration)/$(platform)
      artifactName: ReplayManager-$(platform)
#- job: package
#  steps:
#  - task: 
- job: release
  dependsOn: build_and_publish
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ReplayManager-x64
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ReplayManager-x86
  - task: GitHubRelease@1
    displayName: 'Create GitHub Release'
    # condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')
    inputs:
      gitHubConnection: 'github.com_ThiccDaddie'
      repositoryName: 'ThiccDaddie/ReplayManager'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(Build.BuildNumber)'
      releaseNotesSource: 'inline'
      assets: '$(Pipeline.Workspace)\**\*'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'