// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReplayManager.DataAccess;

#nullable disable

namespace ReplayManager.Migrations
{
    [DbContext(typeof(ReplaysContext))]
    [Migration("20211202213433_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ReplayManager.Models.ReplayInfo", b =>
                {
                    b.Property<string>("Directory")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("BattleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientVersionFromXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFilePresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerVehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Directory", "RelativeFilePath");

                    b.ToTable("Replays");
                });
#pragma warning restore 612, 618
        }
    }
}
