// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReplayManager.DataAccess;

namespace ReplayManager.Migrations
{
    [DbContext(typeof(ReplaysContext))]
    partial class ReplaysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ReplayManager.Shared.ReplayInfo", b =>
                {
                    b.Property<string>("ReplayInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BattleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientVersionFromExe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFilePresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerVehicle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.HasKey("ReplayInfoId");

                    b.ToTable("Replays");
                });
#pragma warning restore 612, 618
        }
    }
}
